
// //----------------------------------------------------
// // The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
// //----------------------------------------------------

// package br.maua.cic303;

// import java_cup.runtime.*;
// import java_cup.runtime.XMLElement;

// /** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
//   */
// @SuppressWarnings({"rawtypes"})
// public class parser extends java_cup.runtime.lr_parser {

//  public final Class getSymbolContainer() {
//     return sym.class;
// }

//   /** Default constructor. */
//   @Deprecated
//   public parser() {super();}

//   /** Constructor which sets the default scanner. */
//   @Deprecated
//   public parser(java_cup.runtime.Scanner s) {super(s);}

//   /** Constructor which sets the default scanner. */
//   public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

//   /** Production table. */
//   protected static final short _production_table[][] = 
//     unpackFromStrings(new String[] {
//     "\000\025\000\002\002\004\000\002\002\003\000\002\003" +
//     "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
//     "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
//     "\002\005\006\000\002\006\010\000\002\006\012\000\002" +
//     "\007\007\000\002\010\005\000\002\011\003\000\002\012" +
//     "\005\000\002\012\005\000\002\012\005\000\002\012\005" +
//     "\000\002\012\003\000\002\012\003" });

//   /** Access to production table. */
//   public short[][] production_table() {return _production_table;}

//   /** Parse-action table. */
//   protected static final short[][] _action_table = 
//     unpackFromStrings(new String[] {
//     "\000\053\000\014\004\015\007\004\013\005\015\012\016" +
//     "\017\001\002\000\004\011\052\001\002\000\014\004\015" +
//     "\007\004\013\005\015\012\016\017\001\002\000\020\002" +
//     "\ufffc\004\ufffc\007\ufffc\013\ufffc\014\ufffc\015\ufffc\016\ufffc" +
//     "\001\002\000\020\002\ufffe\004\ufffe\007\ufffe\013\ufffe\014" +
//     "\ufffe\015\ufffe\016\ufffe\001\002\000\020\002\ufff9\004\ufff9" +
//     "\007\ufff9\013\ufff9\014\ufff9\015\ufff9\016\ufff9\001\002\000" +
//     "\020\002\ufffd\004\ufffd\007\ufffd\013\ufffd\014\ufffd\015\ufffd" +
//     "\016\ufffd\001\002\000\020\002\ufff3\004\ufff3\007\ufff3\013" +
//     "\ufff3\014\ufff3\015\ufff3\016\ufff3\001\002\000\004\002\047" +
//     "\001\002\000\020\002\ufffb\004\ufffb\007\ufffb\013\ufffb\014" +
//     "\ufffb\015\ufffb\016\ufffb\001\002\000\004\011\040\001\002" +
//     "\000\020\002\ufffa\004\ufffa\007\ufffa\013\ufffa\014\ufffa\015" +
//     "\ufffa\016\ufffa\001\002\000\004\010\022\001\002\000\016" +
//     "\002\000\004\015\007\004\013\005\015\012\016\017\001" +
//     "\002\000\020\002\uffff\004\uffff\007\uffff\013\uffff\014\uffff" +
//     "\015\uffff\016\uffff\001\002\000\010\011\025\016\023\017" +
//     "\024\001\002\000\014\012\uffed\015\uffed\020\uffed\021\uffed" +
//     "\022\uffed\001\002\000\014\012\uffee\015\uffee\020\uffee\021" +
//     "\uffee\022\uffee\001\002\000\010\011\025\016\023\017\024" +
//     "\001\002\000\012\015\032\020\030\021\031\022\027\001" +
//     "\002\000\010\011\025\016\023\017\024\001\002\000\010" +
//     "\011\025\016\023\017\024\001\002\000\010\011\025\016" +
//     "\023\017\024\001\002\000\020\002\ufff8\004\ufff8\007\ufff8" +
//     "\013\ufff8\014\ufff8\015\ufff8\016\ufff8\001\002\000\014\012" +
//     "\ufff1\015\ufff1\020\ufff1\021\ufff1\022\ufff1\001\002\000\014" +
//     "\012\ufff2\015\ufff2\020\ufff2\021\031\022\ufff2\001\002\000" +
//     "\014\012\ufff0\015\ufff0\020\030\021\031\022\ufff0\001\002" +
//     "\000\012\012\037\020\030\021\031\022\027\001\002\000" +
//     "\014\012\uffef\015\uffef\020\uffef\021\uffef\022\uffef\001\002" +
//     "\000\010\011\025\016\023\017\024\001\002\000\012\012" +
//     "\042\020\030\021\031\022\027\001\002\000\004\005\043" +
//     "\001\002\000\004\013\005\001\002\000\022\002\ufff7\004" +
//     "\ufff7\006\045\007\ufff7\013\ufff7\014\ufff7\015\ufff7\016\ufff7" +
//     "\001\002\000\004\013\005\001\002\000\020\002\ufff6\004" +
//     "\ufff6\007\ufff6\013\ufff6\014\ufff6\015\ufff6\016\ufff6\001\002" +
//     "\000\004\002\001\001\002\000\016\004\015\007\004\013" +
//     "\005\014\051\015\012\016\017\001\002\000\022\002\ufff4" +
//     "\004\ufff4\006\ufff4\007\ufff4\013\ufff4\014\ufff4\015\ufff4\016" +
//     "\ufff4\001\002\000\010\011\025\016\023\017\024\001\002" +
//     "\000\012\012\054\020\030\021\031\022\027\001\002\000" +
//     "\004\013\005\001\002\000\020\002\ufff5\004\ufff5\007\ufff5" +
//     "\013\ufff5\014\ufff5\015\ufff5\016\ufff5\001\002" });

//   /** Access to parse-action table. */
//   public short[][] action_table() {return _action_table;}

//   /** <code>reduce_goto</code> table. */
//   protected static final short[][] _reduce_table = 
//     unpackFromStrings(new String[] {
//     "\000\053\000\022\002\012\003\017\004\006\005\010\006" +
//     "\005\007\013\010\015\011\007\001\001\000\002\001\001" +
//     "\000\020\003\047\004\006\005\010\006\005\007\013\010" +
//     "\015\011\007\001\001\000\002\001\001\000\002\001\001" +
//     "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
//     "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
//     "\001\001\000\002\001\001\000\016\004\020\005\010\006" +
//     "\005\007\013\010\015\011\007\001\001\000\002\001\001" +
//     "\000\004\012\025\001\001\000\002\001\001\000\002\001" +
//     "\001\000\004\012\035\001\001\000\002\001\001\000\004" +
//     "\012\034\001\001\000\004\012\033\001\001\000\004\012" +
//     "\032\001\001\000\002\001\001\000\002\001\001\000\002" +
//     "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
//     "\001\000\004\012\040\001\001\000\002\001\001\000\002" +
//     "\001\001\000\004\010\043\001\001\000\002\001\001\000" +
//     "\004\010\045\001\001\000\002\001\001\000\002\001\001" +
//     "\000\016\004\020\005\010\006\005\007\013\010\015\011" +
//     "\007\001\001\000\002\001\001\000\004\012\052\001\001" +
//     "\000\002\001\001\000\004\010\054\001\001\000\002\001" +
//     "\001" });

//   /** Access to <code>reduce_goto</code> table. */
//   public short[][] reduce_table() {return _reduce_table;}

//   /** Instance of action encapsulation class. */
//   protected CUP$parser$actions action_obj;

//   /** Action encapsulation object initializer. */
//   protected void init_actions()
//     {
//       action_obj = new CUP$parser$actions(this);
//     }

//   /** Invoke a user supplied parse action. */
//   public java_cup.runtime.Symbol do_action(
//     int                        act_num,
//     java_cup.runtime.lr_parser parser,
//     java.util.Stack            stack,
//     int                        top)
//     throws java.lang.Exception
//   {
//     /* call code in generated class */
//     return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
//   }

//   /** Indicates start state. */
//   public int start_state() {return 0;}
//   /** Indicates start production. */
//   public int start_production() {return 0;}

//   /** <code>EOF</code> Symbol index. */
//   public int EOF_sym() {return 0;}

//   /** <code>error</code> Symbol index. */
//   public int error_sym() {return 1;}



//     public void syntax_error(Symbol cur_token) {
//         throw new RuntimeException("Erro Sintático na linha " + cur_token.left + ", coluna " + cur_token.right);
//     }


// /** Cup generated class to encapsulate user supplied action code.*/
// @SuppressWarnings({"rawtypes", "unchecked", "unused"})
// class CUP$parser$actions {
//   private final parser parser;

//   /** Constructor */
//   CUP$parser$actions(parser parser) {
//     this.parser = parser;
//   }

//   /** Method 0 with the actual generated action code for actions 0 to 300. */
//   public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
//     int                        CUP$parser$act_num,
//     java_cup.runtime.lr_parser CUP$parser$parser,
//     java.util.Stack            CUP$parser$stack,
//     int                        CUP$parser$top)
//     throws java.lang.Exception
//     {
//       /* Symbol object for return from actions */
//       java_cup.runtime.Symbol CUP$parser$result;

//       /* select the action based on the action number */
//       switch (CUP$parser$act_num)
//         {
//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 0: // $START ::= program EOF 
//             {
//               Object RESULT =null;
// 		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
// 		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
// 		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
// 		RESULT = start_val;
//               CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           /* ACCEPT */
//           CUP$parser$parser.done_parsing();
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 1: // program ::= stmt_list 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 2: // stmt_list ::= stmt_list stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 3: // stmt_list ::= stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 4: // stmt ::= assign_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 5: // stmt ::= if_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 6: // stmt ::= while_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 7: // stmt ::= block_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 8: // stmt ::= null_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 9: // assign_stmt ::= ID ASSIGN expr SEMI 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("assign_stmt",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 10: // if_stmt ::= IF LPAREN expr RPAREN THEN block_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 11: // if_stmt ::= IF LPAREN expr RPAREN THEN block_stmt ELSE block_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 12: // while_stmt ::= WHILE LPAREN expr RPAREN block_stmt 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 13: // block_stmt ::= LBRACE stmt_list RBRACE 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("block_stmt",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 14: // null_stmt ::= SEMI 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("null_stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 15: // expr ::= expr ADD_OP expr 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 16: // expr ::= expr MUL_OP expr 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 17: // expr ::= expr REL_OP expr 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 18: // expr ::= LPAREN expr RPAREN 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 19: // expr ::= NUMBER 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /*. . . . . . . . . . . . . . . . . . . .*/
//           case 20: // expr ::= ID 
//             {
//               Object RESULT =null;

//               CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
//             }
//           return CUP$parser$result;

//           /* . . . . . .*/
//           default:
//             throw new Exception(
//                "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

//         }
//     } /* end of method */

//   /** Method splitting the generated action code into several parts. */
//   public final java_cup.runtime.Symbol CUP$parser$do_action(
//     int                        CUP$parser$act_num,
//     java_cup.runtime.lr_parser CUP$parser$parser,
//     java.util.Stack            CUP$parser$stack,
//     int                        CUP$parser$top)
//     throws java.lang.Exception
//     {
//               return CUP$parser$do_action_part00000000(
//                                CUP$parser$act_num,
//                                CUP$parser$parser,
//                                CUP$parser$stack,
//                                CUP$parser$top);
//     }
// }

// }
