
// //----------------------------------------------------
// // The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
// //----------------------------------------------------

// package br.maua.cic303;

// /** CUP generated class containing symbol constants. */
// public class sym {
//   /* terminals */
//   public static final int REL_OP = 16;
//   public static final int LBRACE = 9;
//   public static final int WHILE = 5;
//   public static final int MUL_OP = 15;
//   public static final int NUMBER = 13;
//   public static final int THEN = 3;
//   public static final int SEMI = 11;
//   public static final int EOF = 0;
//   public static final int IF = 2;
//   public static final int ID = 12;
//   public static final int ELSE = 4;
//   public static final int ASSIGN = 6;
//   public static final int error = 1;
//   public static final int RPAREN = 8;
//   public static final int ADD_OP = 14;
//   public static final int RBRACE = 10;
//   public static final int LPAREN = 7;
//   public static final String[] terminalNames = new String[] {
//   "EOF",
//   "error",
//   "IF",
//   "THEN",
//   "ELSE",
//   "WHILE",
//   "ASSIGN",
//   "LPAREN",
//   "RPAREN",
//   "LBRACE",
//   "RBRACE",
//   "SEMI",
//   "ID",
//   "NUMBER",
//   "ADD_OP",
//   "MUL_OP",
//   "REL_OP"
//   };
// }

